# Base setup
- hosts: masters, workers
  tasks:
  - lineinfile:
      dest: /etc/sudoers
      line: 'Defaults requiretty'
      state: absent
    vars:
      ansible_ssh_pipelining: no
  - include: tasks/setup_libvirt.yml
  - include: tasks/setup_vm_net.yml
  - include: tasks/define_vms.yml

# Master VMs
- hosts: masters
  tasks:
  - name: "disable unused services"
    service: name={{item}} state=stopped enabled=no
    register: unused_disable
    failed_when: "unused_disable|failed and ('find' not in unused_disable.msg and 'found' not in unused_disable.msg)"
    with_items:
      - dnsmasq
      - matchbox

# Configure and start dnsmasq, matchbox and installer and start VMs
- hosts: masters,workers
  tasks:
  - name: list VMs
    virt:
      command: list_vms
    register: virt_vms

  - name: get VM info
    virt:
      command: info
    register: virt_info

  - name: get VM mac addresses
    shell: "virsh domiflist {{item}} | sed '1d;2d' | awk '{print $5}'"
    register: vm_interfaces
    with_items: "{{virt_vms.list_vms}}"

  - include: tasks/setup_dnsmasq.yml
    when: ansible_hostname == 'master'

  - include: tasks/setup_matchbox.yml
    when: ansible_hostname == 'master'

  - include: tasks/setup_kubectl.yml
    when: ansible_hostname == 'master'

  - include: tasks/setup_tectonic_installer.yml
    when: ansible_hostname == 'master'

# Run installer
- hosts: all

  vars:
    tf_env:
      INSTALLER_PATH: "/opt/tectonic_1.8.4-tectonic.3/tectonic-installer/linux/installer"
      PATH: "/opt/tectonic_1.8.4-tectonic.3/tectonic-installer/linux:$PATH"
      CLUSTER: prom-scale-test
      TF_VAR_tectonic_admin_email: "admin@example.com"
      TF_VAR_tectonic_admin_password: "pl41nT3xt"

  tasks:
  - name: initialize terraform
    shell: terraform init ./platforms/metal
    args:
      chdir: "/opt/tectonic_1.8.4-tectonic.3/"
    environment: "{{tf_env}}"
    when: ansible_hostname == 'master'

  - name: hotfix installer
    template:
      src: templates/tf_module_container_linux_main.tf.tpl
      dest: "/opt/tectonic_1.8.4-tectonic.3/modules/container_linux/main.tf"
      owner: root
      group: root
      mode: 0644
    when: ansible_hostname == 'master'

  - name: run terraform plan
    shell: terraform plan -var-file=build/prom-scale-test/terraform.tfvars platforms/metal
    args:
      chdir: "/opt/tectonic_1.8.4-tectonic.3/"
    environment: "{{tf_env}}"
    when: ansible_hostname == 'master'

  - name: write terraform.env file
    template:
      src: templates/terraform.env.tpl
      dest: /tmp/terraform.env
      owner: root
      group: root
      mode: 0644

  - name: run terraform apply
    command: terraform apply -var-file=build/prom-scale-test/terraform.tfvars platforms/metal
    args:
      chdir: "/opt/tectonic_1.8.4-tectonic.3/"
    environment: "{{tf_env}}"
    when: ansible_hostname == 'master'
    become_flags: "-E"
    async: 300
    poll: 0
    register: tfrun

  - pause:
      seconds: 60

  - name: list VMs
    virt:
      command: list_vms
    register: virt_vms

  - name: get guest info
    virt:
      command: info
    register: virt_info

  - name: start all VMs
    virt:
      name: "{{item}}"
      command: start
    when: virt_info[item]['state'] != 'running'
    with_items: "{{ virt_vms.list_vms }}"

  - name: check terraform apply
    async_status:
      jid: "{{ tfrun.ansible_job_id }}"
    when: ansible_hostname == 'master'
    register: job_result
    until: job_result.finished
    retries: 30
